#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TQM.DataEntity
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TQM")]
	public partial class TQMDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblCarBrand(tblCarBrand instance);
    partial void UpdatetblCarBrand(tblCarBrand instance);
    partial void DeletetblCarBrand(tblCarBrand instance);
    partial void InserttblCarModel(tblCarModel instance);
    partial void UpdatetblCarModel(tblCarModel instance);
    partial void DeletetblCarModel(tblCarModel instance);
    partial void InserttblCarSubModel(tblCarSubModel instance);
    partial void UpdatetblCarSubModel(tblCarSubModel instance);
    partial void DeletetblCarSubModel(tblCarSubModel instance);
    partial void InserttblCarCC(tblCarCC instance);
    partial void UpdatetblCarCC(tblCarCC instance);
    partial void DeletetblCarCC(tblCarCC instance);
    partial void InserttblCarSubModelCC(tblCarSubModelCC instance);
    partial void UpdatetblCarSubModelCC(tblCarSubModelCC instance);
    partial void DeletetblCarSubModelCC(tblCarSubModelCC instance);
    partial void InserttblMotorCoverage(tblMotorCoverage instance);
    partial void UpdatetblMotorCoverage(tblMotorCoverage instance);
    partial void DeletetblMotorCoverage(tblMotorCoverage instance);
    partial void InserttblGarage(tblGarage instance);
    partial void UpdatetblGarage(tblGarage instance);
    partial void DeletetblGarage(tblGarage instance);
    partial void InserttblMotorSearch(tblMotorSearch instance);
    partial void UpdatetblMotorSearch(tblMotorSearch instance);
    partial void DeletetblMotorSearch(tblMotorSearch instance);
    partial void InserttblCarSubModelSumInsured(tblCarSubModelSumInsured instance);
    partial void UpdatetblCarSubModelSumInsured(tblCarSubModelSumInsured instance);
    partial void DeletetblCarSubModelSumInsured(tblCarSubModelSumInsured instance);
    #endregion
		
		public TQMDataContext() : 
				base(global::TQM.Properties.Settings.Default.TQMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TQMDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TQMDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TQMDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TQMDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblCarBrand> tblCarBrands
		{
			get
			{
				return this.GetTable<tblCarBrand>();
			}
		}
		
		public System.Data.Linq.Table<tblCarModel> tblCarModels
		{
			get
			{
				return this.GetTable<tblCarModel>();
			}
		}
		
		public System.Data.Linq.Table<tblCarSubModel> tblCarSubModels
		{
			get
			{
				return this.GetTable<tblCarSubModel>();
			}
		}
		
		public System.Data.Linq.Table<tblCarCC> tblCarCCs
		{
			get
			{
				return this.GetTable<tblCarCC>();
			}
		}
		
		public System.Data.Linq.Table<tblCarSubModelCC> tblCarSubModelCCs
		{
			get
			{
				return this.GetTable<tblCarSubModelCC>();
			}
		}
		
		public System.Data.Linq.Table<tblMotorCoverage> tblMotorCoverages
		{
			get
			{
				return this.GetTable<tblMotorCoverage>();
			}
		}
		
		public System.Data.Linq.Table<tblGarage> tblGarages
		{
			get
			{
				return this.GetTable<tblGarage>();
			}
		}
		
		public System.Data.Linq.Table<V_Search> V_Searches
		{
			get
			{
				return this.GetTable<V_Search>();
			}
		}
		
		public System.Data.Linq.Table<tblMotorSearch> tblMotorSearches
		{
			get
			{
				return this.GetTable<tblMotorSearch>();
			}
		}
		
		public System.Data.Linq.Table<tblCarSubModelSumInsured> tblCarSubModelSumInsureds
		{
			get
			{
				return this.GetTable<tblCarSubModelSumInsured>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCarBrand")]
	public partial class tblCarBrand : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CarBrandCode;
		
		private string _CarBrandName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCarBrandCodeChanging(string value);
    partial void OnCarBrandCodeChanged();
    partial void OnCarBrandNameChanging(string value);
    partial void OnCarBrandNameChanged();
    #endregion
		
		public tblCarBrand()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarBrandCode", DbType="VarChar(4) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CarBrandCode
		{
			get
			{
				return this._CarBrandCode;
			}
			set
			{
				if ((this._CarBrandCode != value))
				{
					this.OnCarBrandCodeChanging(value);
					this.SendPropertyChanging();
					this._CarBrandCode = value;
					this.SendPropertyChanged("CarBrandCode");
					this.OnCarBrandCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarBrandName", DbType="VarChar(50)")]
		public string CarBrandName
		{
			get
			{
				return this._CarBrandName;
			}
			set
			{
				if ((this._CarBrandName != value))
				{
					this.OnCarBrandNameChanging(value);
					this.SendPropertyChanging();
					this._CarBrandName = value;
					this.SendPropertyChanged("CarBrandName");
					this.OnCarBrandNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCarModel")]
	public partial class tblCarModel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CarModelCode;
		
		private string _CarModelName;
		
		private string _CarBrandCode;
		
		private string _CarYear;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCarModelCodeChanging(string value);
    partial void OnCarModelCodeChanged();
    partial void OnCarModelNameChanging(string value);
    partial void OnCarModelNameChanged();
    partial void OnCarBrandCodeChanging(string value);
    partial void OnCarBrandCodeChanged();
    partial void OnCarYearChanging(string value);
    partial void OnCarYearChanged();
    #endregion
		
		public tblCarModel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarModelCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CarModelCode
		{
			get
			{
				return this._CarModelCode;
			}
			set
			{
				if ((this._CarModelCode != value))
				{
					this.OnCarModelCodeChanging(value);
					this.SendPropertyChanging();
					this._CarModelCode = value;
					this.SendPropertyChanged("CarModelCode");
					this.OnCarModelCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarModelName", DbType="VarChar(255)")]
		public string CarModelName
		{
			get
			{
				return this._CarModelName;
			}
			set
			{
				if ((this._CarModelName != value))
				{
					this.OnCarModelNameChanging(value);
					this.SendPropertyChanging();
					this._CarModelName = value;
					this.SendPropertyChanged("CarModelName");
					this.OnCarModelNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarBrandCode", DbType="VarChar(4)")]
		public string CarBrandCode
		{
			get
			{
				return this._CarBrandCode;
			}
			set
			{
				if ((this._CarBrandCode != value))
				{
					this.OnCarBrandCodeChanging(value);
					this.SendPropertyChanging();
					this._CarBrandCode = value;
					this.SendPropertyChanged("CarBrandCode");
					this.OnCarBrandCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarYear", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CarYear
		{
			get
			{
				return this._CarYear;
			}
			set
			{
				if ((this._CarYear != value))
				{
					this.OnCarYearChanging(value);
					this.SendPropertyChanging();
					this._CarYear = value;
					this.SendPropertyChanged("CarYear");
					this.OnCarYearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCarSubModel")]
	public partial class tblCarSubModel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CarSubModelCode;
		
		private string _CarSubModelName;
		
		private string _CarModelCode;
		
		private string _CarBrandCode;
		
		private string _CarYear;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCarSubModelCodeChanging(string value);
    partial void OnCarSubModelCodeChanged();
    partial void OnCarSubModelNameChanging(string value);
    partial void OnCarSubModelNameChanged();
    partial void OnCarModelCodeChanging(string value);
    partial void OnCarModelCodeChanged();
    partial void OnCarBrandCodeChanging(string value);
    partial void OnCarBrandCodeChanged();
    partial void OnCarYearChanging(string value);
    partial void OnCarYearChanged();
    #endregion
		
		public tblCarSubModel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarSubModelCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CarSubModelCode
		{
			get
			{
				return this._CarSubModelCode;
			}
			set
			{
				if ((this._CarSubModelCode != value))
				{
					this.OnCarSubModelCodeChanging(value);
					this.SendPropertyChanging();
					this._CarSubModelCode = value;
					this.SendPropertyChanged("CarSubModelCode");
					this.OnCarSubModelCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarSubModelName", DbType="VarChar(255)")]
		public string CarSubModelName
		{
			get
			{
				return this._CarSubModelName;
			}
			set
			{
				if ((this._CarSubModelName != value))
				{
					this.OnCarSubModelNameChanging(value);
					this.SendPropertyChanging();
					this._CarSubModelName = value;
					this.SendPropertyChanged("CarSubModelName");
					this.OnCarSubModelNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarModelCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CarModelCode
		{
			get
			{
				return this._CarModelCode;
			}
			set
			{
				if ((this._CarModelCode != value))
				{
					this.OnCarModelCodeChanging(value);
					this.SendPropertyChanging();
					this._CarModelCode = value;
					this.SendPropertyChanged("CarModelCode");
					this.OnCarModelCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarBrandCode", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string CarBrandCode
		{
			get
			{
				return this._CarBrandCode;
			}
			set
			{
				if ((this._CarBrandCode != value))
				{
					this.OnCarBrandCodeChanging(value);
					this.SendPropertyChanging();
					this._CarBrandCode = value;
					this.SendPropertyChanged("CarBrandCode");
					this.OnCarBrandCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarYear", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CarYear
		{
			get
			{
				return this._CarYear;
			}
			set
			{
				if ((this._CarYear != value))
				{
					this.OnCarYearChanging(value);
					this.SendPropertyChanging();
					this._CarYear = value;
					this.SendPropertyChanged("CarYear");
					this.OnCarYearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCarCC")]
	public partial class tblCarCC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CarCCCode;
		
		private string _CarCCName;
		
		private string _CarModelCode;
		
		private string _CarBrandCode;
		
		private string _CarYear;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCarCCCodeChanging(string value);
    partial void OnCarCCCodeChanged();
    partial void OnCarCCNameChanging(string value);
    partial void OnCarCCNameChanged();
    partial void OnCarModelCodeChanging(string value);
    partial void OnCarModelCodeChanged();
    partial void OnCarBrandCodeChanging(string value);
    partial void OnCarBrandCodeChanged();
    partial void OnCarYearChanging(string value);
    partial void OnCarYearChanged();
    #endregion
		
		public tblCarCC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarCCCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CarCCCode
		{
			get
			{
				return this._CarCCCode;
			}
			set
			{
				if ((this._CarCCCode != value))
				{
					this.OnCarCCCodeChanging(value);
					this.SendPropertyChanging();
					this._CarCCCode = value;
					this.SendPropertyChanged("CarCCCode");
					this.OnCarCCCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarCCName", DbType="VarChar(255)")]
		public string CarCCName
		{
			get
			{
				return this._CarCCName;
			}
			set
			{
				if ((this._CarCCName != value))
				{
					this.OnCarCCNameChanging(value);
					this.SendPropertyChanging();
					this._CarCCName = value;
					this.SendPropertyChanged("CarCCName");
					this.OnCarCCNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarModelCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CarModelCode
		{
			get
			{
				return this._CarModelCode;
			}
			set
			{
				if ((this._CarModelCode != value))
				{
					this.OnCarModelCodeChanging(value);
					this.SendPropertyChanging();
					this._CarModelCode = value;
					this.SendPropertyChanged("CarModelCode");
					this.OnCarModelCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarBrandCode", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string CarBrandCode
		{
			get
			{
				return this._CarBrandCode;
			}
			set
			{
				if ((this._CarBrandCode != value))
				{
					this.OnCarBrandCodeChanging(value);
					this.SendPropertyChanging();
					this._CarBrandCode = value;
					this.SendPropertyChanged("CarBrandCode");
					this.OnCarBrandCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarYear", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CarYear
		{
			get
			{
				return this._CarYear;
			}
			set
			{
				if ((this._CarYear != value))
				{
					this.OnCarYearChanging(value);
					this.SendPropertyChanging();
					this._CarYear = value;
					this.SendPropertyChanged("CarYear");
					this.OnCarYearChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCarSubModelCC")]
	public partial class tblCarSubModelCC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CarSubModelCCCode;
		
		private string _CarSubModelCCName;
		
		private string _CarModelCode;
		
		private string _CarBrandCode;
		
		private string _CarYear;
		
		private string _CarSubModelCode;
		
		private int _CarSubModelID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCarSubModelCCCodeChanging(string value);
    partial void OnCarSubModelCCCodeChanged();
    partial void OnCarSubModelCCNameChanging(string value);
    partial void OnCarSubModelCCNameChanged();
    partial void OnCarModelCodeChanging(string value);
    partial void OnCarModelCodeChanged();
    partial void OnCarBrandCodeChanging(string value);
    partial void OnCarBrandCodeChanged();
    partial void OnCarYearChanging(string value);
    partial void OnCarYearChanged();
    partial void OnCarSubModelCodeChanging(string value);
    partial void OnCarSubModelCodeChanged();
    partial void OnCarSubModelIDChanging(int value);
    partial void OnCarSubModelIDChanged();
    #endregion
		
		public tblCarSubModelCC()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarSubModelCCCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CarSubModelCCCode
		{
			get
			{
				return this._CarSubModelCCCode;
			}
			set
			{
				if ((this._CarSubModelCCCode != value))
				{
					this.OnCarSubModelCCCodeChanging(value);
					this.SendPropertyChanging();
					this._CarSubModelCCCode = value;
					this.SendPropertyChanged("CarSubModelCCCode");
					this.OnCarSubModelCCCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarSubModelCCName", DbType="VarChar(255)")]
		public string CarSubModelCCName
		{
			get
			{
				return this._CarSubModelCCName;
			}
			set
			{
				if ((this._CarSubModelCCName != value))
				{
					this.OnCarSubModelCCNameChanging(value);
					this.SendPropertyChanging();
					this._CarSubModelCCName = value;
					this.SendPropertyChanged("CarSubModelCCName");
					this.OnCarSubModelCCNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarModelCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CarModelCode
		{
			get
			{
				return this._CarModelCode;
			}
			set
			{
				if ((this._CarModelCode != value))
				{
					this.OnCarModelCodeChanging(value);
					this.SendPropertyChanging();
					this._CarModelCode = value;
					this.SendPropertyChanged("CarModelCode");
					this.OnCarModelCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarBrandCode", DbType="VarChar(4) NOT NULL", CanBeNull=false)]
		public string CarBrandCode
		{
			get
			{
				return this._CarBrandCode;
			}
			set
			{
				if ((this._CarBrandCode != value))
				{
					this.OnCarBrandCodeChanging(value);
					this.SendPropertyChanging();
					this._CarBrandCode = value;
					this.SendPropertyChanged("CarBrandCode");
					this.OnCarBrandCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarYear", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string CarYear
		{
			get
			{
				return this._CarYear;
			}
			set
			{
				if ((this._CarYear != value))
				{
					this.OnCarYearChanging(value);
					this.SendPropertyChanging();
					this._CarYear = value;
					this.SendPropertyChanged("CarYear");
					this.OnCarYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarSubModelCode", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string CarSubModelCode
		{
			get
			{
				return this._CarSubModelCode;
			}
			set
			{
				if ((this._CarSubModelCode != value))
				{
					this.OnCarSubModelCodeChanging(value);
					this.SendPropertyChanging();
					this._CarSubModelCode = value;
					this.SendPropertyChanged("CarSubModelCode");
					this.OnCarSubModelCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarSubModelID", DbType="Int NOT NULL")]
		public int CarSubModelID
		{
			get
			{
				return this._CarSubModelID;
			}
			set
			{
				if ((this._CarSubModelID != value))
				{
					this.OnCarSubModelIDChanging(value);
					this.SendPropertyChanging();
					this._CarSubModelID = value;
					this.SendPropertyChanged("CarSubModelID");
					this.OnCarSubModelIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMotorCoverage")]
	public partial class tblMotorCoverage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private System.Nullable<int> _SearchID;
		
		private string _InsurerImage;
		
		private string _InsurerName;
		
		private string _Premium;
		
		private string _txtInsurerGarage;
		
		private string _txtGarageNo;
		
		private string _txtSuminSured;
		
		private string _txtCheckCar;
		
		private string _txtCoverPirate;
		
		private string _txtCoverFlood;
		
		private string _txtDeduct;
		
		private string _txtCoverTP1;
		
		private string _txtCoverTP2;
		
		private string _txtCoverTP3;
		
		private string _txtCoverBody;
		
		private string _txtCoverFire;
		
		private string _txtCoverPA;
		
		private string _txtCoverMedical;
		
		private string _txtCoverBB;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnSearchIDChanging(System.Nullable<int> value);
    partial void OnSearchIDChanged();
    partial void OnInsurerImageChanging(string value);
    partial void OnInsurerImageChanged();
    partial void OnInsurerNameChanging(string value);
    partial void OnInsurerNameChanged();
    partial void OnPremiumChanging(string value);
    partial void OnPremiumChanged();
    partial void OntxtInsurerGarageChanging(string value);
    partial void OntxtInsurerGarageChanged();
    partial void OntxtGarageNoChanging(string value);
    partial void OntxtGarageNoChanged();
    partial void OntxtSuminSuredChanging(string value);
    partial void OntxtSuminSuredChanged();
    partial void OntxtCheckCarChanging(string value);
    partial void OntxtCheckCarChanged();
    partial void OntxtCoverPirateChanging(string value);
    partial void OntxtCoverPirateChanged();
    partial void OntxtCoverFloodChanging(string value);
    partial void OntxtCoverFloodChanged();
    partial void OntxtDeductChanging(string value);
    partial void OntxtDeductChanged();
    partial void OntxtCoverTP1Changing(string value);
    partial void OntxtCoverTP1Changed();
    partial void OntxtCoverTP2Changing(string value);
    partial void OntxtCoverTP2Changed();
    partial void OntxtCoverTP3Changing(string value);
    partial void OntxtCoverTP3Changed();
    partial void OntxtCoverBodyChanging(string value);
    partial void OntxtCoverBodyChanged();
    partial void OntxtCoverFireChanging(string value);
    partial void OntxtCoverFireChanged();
    partial void OntxtCoverPAChanging(string value);
    partial void OntxtCoverPAChanged();
    partial void OntxtCoverMedicalChanging(string value);
    partial void OntxtCoverMedicalChanged();
    partial void OntxtCoverBBChanging(string value);
    partial void OntxtCoverBBChanged();
    #endregion
		
		public tblMotorCoverage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SearchID", DbType="Int")]
		public System.Nullable<int> SearchID
		{
			get
			{
				return this._SearchID;
			}
			set
			{
				if ((this._SearchID != value))
				{
					this.OnSearchIDChanging(value);
					this.SendPropertyChanging();
					this._SearchID = value;
					this.SendPropertyChanged("SearchID");
					this.OnSearchIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsurerImage", DbType="VarChar(255)")]
		public string InsurerImage
		{
			get
			{
				return this._InsurerImage;
			}
			set
			{
				if ((this._InsurerImage != value))
				{
					this.OnInsurerImageChanging(value);
					this.SendPropertyChanging();
					this._InsurerImage = value;
					this.SendPropertyChanged("InsurerImage");
					this.OnInsurerImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InsurerName", DbType="VarChar(255)")]
		public string InsurerName
		{
			get
			{
				return this._InsurerName;
			}
			set
			{
				if ((this._InsurerName != value))
				{
					this.OnInsurerNameChanging(value);
					this.SendPropertyChanging();
					this._InsurerName = value;
					this.SendPropertyChanged("InsurerName");
					this.OnInsurerNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Premium", DbType="VarChar(255)")]
		public string Premium
		{
			get
			{
				return this._Premium;
			}
			set
			{
				if ((this._Premium != value))
				{
					this.OnPremiumChanging(value);
					this.SendPropertyChanging();
					this._Premium = value;
					this.SendPropertyChanged("Premium");
					this.OnPremiumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtInsurerGarage", DbType="VarChar(255)")]
		public string txtInsurerGarage
		{
			get
			{
				return this._txtInsurerGarage;
			}
			set
			{
				if ((this._txtInsurerGarage != value))
				{
					this.OntxtInsurerGarageChanging(value);
					this.SendPropertyChanging();
					this._txtInsurerGarage = value;
					this.SendPropertyChanged("txtInsurerGarage");
					this.OntxtInsurerGarageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtGarageNo", DbType="VarChar(255)")]
		public string txtGarageNo
		{
			get
			{
				return this._txtGarageNo;
			}
			set
			{
				if ((this._txtGarageNo != value))
				{
					this.OntxtGarageNoChanging(value);
					this.SendPropertyChanging();
					this._txtGarageNo = value;
					this.SendPropertyChanged("txtGarageNo");
					this.OntxtGarageNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtSuminSured", DbType="VarChar(255)")]
		public string txtSuminSured
		{
			get
			{
				return this._txtSuminSured;
			}
			set
			{
				if ((this._txtSuminSured != value))
				{
					this.OntxtSuminSuredChanging(value);
					this.SendPropertyChanging();
					this._txtSuminSured = value;
					this.SendPropertyChanged("txtSuminSured");
					this.OntxtSuminSuredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtCheckCar", DbType="VarChar(255)")]
		public string txtCheckCar
		{
			get
			{
				return this._txtCheckCar;
			}
			set
			{
				if ((this._txtCheckCar != value))
				{
					this.OntxtCheckCarChanging(value);
					this.SendPropertyChanging();
					this._txtCheckCar = value;
					this.SendPropertyChanged("txtCheckCar");
					this.OntxtCheckCarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtCoverPirate", DbType="VarChar(255)")]
		public string txtCoverPirate
		{
			get
			{
				return this._txtCoverPirate;
			}
			set
			{
				if ((this._txtCoverPirate != value))
				{
					this.OntxtCoverPirateChanging(value);
					this.SendPropertyChanging();
					this._txtCoverPirate = value;
					this.SendPropertyChanged("txtCoverPirate");
					this.OntxtCoverPirateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtCoverFlood", DbType="VarChar(255)")]
		public string txtCoverFlood
		{
			get
			{
				return this._txtCoverFlood;
			}
			set
			{
				if ((this._txtCoverFlood != value))
				{
					this.OntxtCoverFloodChanging(value);
					this.SendPropertyChanging();
					this._txtCoverFlood = value;
					this.SendPropertyChanged("txtCoverFlood");
					this.OntxtCoverFloodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtDeduct", DbType="VarChar(255)")]
		public string txtDeduct
		{
			get
			{
				return this._txtDeduct;
			}
			set
			{
				if ((this._txtDeduct != value))
				{
					this.OntxtDeductChanging(value);
					this.SendPropertyChanging();
					this._txtDeduct = value;
					this.SendPropertyChanged("txtDeduct");
					this.OntxtDeductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtCoverTP1", DbType="VarChar(255)")]
		public string txtCoverTP1
		{
			get
			{
				return this._txtCoverTP1;
			}
			set
			{
				if ((this._txtCoverTP1 != value))
				{
					this.OntxtCoverTP1Changing(value);
					this.SendPropertyChanging();
					this._txtCoverTP1 = value;
					this.SendPropertyChanged("txtCoverTP1");
					this.OntxtCoverTP1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtCoverTP2", DbType="VarChar(255)")]
		public string txtCoverTP2
		{
			get
			{
				return this._txtCoverTP2;
			}
			set
			{
				if ((this._txtCoverTP2 != value))
				{
					this.OntxtCoverTP2Changing(value);
					this.SendPropertyChanging();
					this._txtCoverTP2 = value;
					this.SendPropertyChanged("txtCoverTP2");
					this.OntxtCoverTP2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtCoverTP3", DbType="VarChar(255)")]
		public string txtCoverTP3
		{
			get
			{
				return this._txtCoverTP3;
			}
			set
			{
				if ((this._txtCoverTP3 != value))
				{
					this.OntxtCoverTP3Changing(value);
					this.SendPropertyChanging();
					this._txtCoverTP3 = value;
					this.SendPropertyChanged("txtCoverTP3");
					this.OntxtCoverTP3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtCoverBody", DbType="VarChar(255)")]
		public string txtCoverBody
		{
			get
			{
				return this._txtCoverBody;
			}
			set
			{
				if ((this._txtCoverBody != value))
				{
					this.OntxtCoverBodyChanging(value);
					this.SendPropertyChanging();
					this._txtCoverBody = value;
					this.SendPropertyChanged("txtCoverBody");
					this.OntxtCoverBodyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtCoverFire", DbType="VarChar(255)")]
		public string txtCoverFire
		{
			get
			{
				return this._txtCoverFire;
			}
			set
			{
				if ((this._txtCoverFire != value))
				{
					this.OntxtCoverFireChanging(value);
					this.SendPropertyChanging();
					this._txtCoverFire = value;
					this.SendPropertyChanged("txtCoverFire");
					this.OntxtCoverFireChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtCoverPA", DbType="VarChar(255)")]
		public string txtCoverPA
		{
			get
			{
				return this._txtCoverPA;
			}
			set
			{
				if ((this._txtCoverPA != value))
				{
					this.OntxtCoverPAChanging(value);
					this.SendPropertyChanging();
					this._txtCoverPA = value;
					this.SendPropertyChanged("txtCoverPA");
					this.OntxtCoverPAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtCoverMedical", DbType="VarChar(255)")]
		public string txtCoverMedical
		{
			get
			{
				return this._txtCoverMedical;
			}
			set
			{
				if ((this._txtCoverMedical != value))
				{
					this.OntxtCoverMedicalChanging(value);
					this.SendPropertyChanging();
					this._txtCoverMedical = value;
					this.SendPropertyChanged("txtCoverMedical");
					this.OntxtCoverMedicalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtCoverBB", DbType="VarChar(255)")]
		public string txtCoverBB
		{
			get
			{
				return this._txtCoverBB;
			}
			set
			{
				if ((this._txtCoverBB != value))
				{
					this.OntxtCoverBBChanging(value);
					this.SendPropertyChanging();
					this._txtCoverBB = value;
					this.SendPropertyChanged("txtCoverBB");
					this.OntxtCoverBBChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblGarage")]
	public partial class tblGarage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _GarageID;
		
		private string _GarageName;
		
		private string _GarageType;
		
		private string _Address;
		
		private string _Tel;
		
		private string _Fax;
		
		private string _Url;
		
		private string _gps;
		
		private string _insurer;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnGarageIDChanging(int value);
    partial void OnGarageIDChanged();
    partial void OnGarageNameChanging(string value);
    partial void OnGarageNameChanged();
    partial void OnGarageTypeChanging(string value);
    partial void OnGarageTypeChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnTelChanging(string value);
    partial void OnTelChanged();
    partial void OnFaxChanging(string value);
    partial void OnFaxChanged();
    partial void OnUrlChanging(string value);
    partial void OnUrlChanged();
    partial void OngpsChanging(string value);
    partial void OngpsChanged();
    partial void OninsurerChanging(string value);
    partial void OninsurerChanged();
    #endregion
		
		public tblGarage()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GarageID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int GarageID
		{
			get
			{
				return this._GarageID;
			}
			set
			{
				if ((this._GarageID != value))
				{
					this.OnGarageIDChanging(value);
					this.SendPropertyChanging();
					this._GarageID = value;
					this.SendPropertyChanged("GarageID");
					this.OnGarageIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GarageName", DbType="VarChar(255)")]
		public string GarageName
		{
			get
			{
				return this._GarageName;
			}
			set
			{
				if ((this._GarageName != value))
				{
					this.OnGarageNameChanging(value);
					this.SendPropertyChanging();
					this._GarageName = value;
					this.SendPropertyChanged("GarageName");
					this.OnGarageNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GarageType", DbType="VarChar(255)")]
		public string GarageType
		{
			get
			{
				return this._GarageType;
			}
			set
			{
				if ((this._GarageType != value))
				{
					this.OnGarageTypeChanging(value);
					this.SendPropertyChanging();
					this._GarageType = value;
					this.SendPropertyChanged("GarageType");
					this.OnGarageTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Address", DbType="VarChar(255)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tel", DbType="VarChar(255)")]
		public string Tel
		{
			get
			{
				return this._Tel;
			}
			set
			{
				if ((this._Tel != value))
				{
					this.OnTelChanging(value);
					this.SendPropertyChanging();
					this._Tel = value;
					this.SendPropertyChanged("Tel");
					this.OnTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fax", DbType="VarChar(255)")]
		public string Fax
		{
			get
			{
				return this._Fax;
			}
			set
			{
				if ((this._Fax != value))
				{
					this.OnFaxChanging(value);
					this.SendPropertyChanging();
					this._Fax = value;
					this.SendPropertyChanged("Fax");
					this.OnFaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="VarChar(255)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this.OnUrlChanging(value);
					this.SendPropertyChanging();
					this._Url = value;
					this.SendPropertyChanged("Url");
					this.OnUrlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gps", DbType="VarChar(255)")]
		public string gps
		{
			get
			{
				return this._gps;
			}
			set
			{
				if ((this._gps != value))
				{
					this.OngpsChanging(value);
					this.SendPropertyChanging();
					this._gps = value;
					this.SendPropertyChanged("gps");
					this.OngpsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_insurer", DbType="VarChar(MAX)")]
		public string insurer
		{
			get
			{
				return this._insurer;
			}
			set
			{
				if ((this._insurer != value))
				{
					this.OninsurerChanging(value);
					this.SendPropertyChanging();
					this._insurer = value;
					this.SendPropertyChanged("insurer");
					this.OninsurerChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.V_Search")]
	public partial class V_Search
	{
		
		private string _categories_insurance_year;
		
		private string _categories_insurance_brand;
		
		private string _categories_insurance_age;
		
		private string _CarSubModelCode;
		
		private string _categories_insurance_cc;
		
		private string _VEHICLEKEY;
		
		private string _CarSubModelName;
		
		private string _CarCCName;
		
		private System.Nullable<int> _CoverMin;
		
		private System.Nullable<int> _CoverMax;
		
		public V_Search()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories_insurance_year", DbType="VarChar(10)")]
		public string categories_insurance_year
		{
			get
			{
				return this._categories_insurance_year;
			}
			set
			{
				if ((this._categories_insurance_year != value))
				{
					this._categories_insurance_year = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories_insurance_brand", DbType="VarChar(4)")]
		public string categories_insurance_brand
		{
			get
			{
				return this._categories_insurance_brand;
			}
			set
			{
				if ((this._categories_insurance_brand != value))
				{
					this._categories_insurance_brand = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories_insurance_age", DbType="VarChar(50)")]
		public string categories_insurance_age
		{
			get
			{
				return this._categories_insurance_age;
			}
			set
			{
				if ((this._categories_insurance_age != value))
				{
					this._categories_insurance_age = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarSubModelCode", DbType="VarChar(50)")]
		public string CarSubModelCode
		{
			get
			{
				return this._CarSubModelCode;
			}
			set
			{
				if ((this._CarSubModelCode != value))
				{
					this._CarSubModelCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_categories_insurance_cc", DbType="VarChar(50)")]
		public string categories_insurance_cc
		{
			get
			{
				return this._categories_insurance_cc;
			}
			set
			{
				if ((this._categories_insurance_cc != value))
				{
					this._categories_insurance_cc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VEHICLEKEY", DbType="VarChar(50)")]
		public string VEHICLEKEY
		{
			get
			{
				return this._VEHICLEKEY;
			}
			set
			{
				if ((this._VEHICLEKEY != value))
				{
					this._VEHICLEKEY = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarSubModelName", DbType="VarChar(255)")]
		public string CarSubModelName
		{
			get
			{
				return this._CarSubModelName;
			}
			set
			{
				if ((this._CarSubModelName != value))
				{
					this._CarSubModelName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarCCName", DbType="VarChar(255)")]
		public string CarCCName
		{
			get
			{
				return this._CarCCName;
			}
			set
			{
				if ((this._CarCCName != value))
				{
					this._CarCCName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoverMin", DbType="Int")]
		public System.Nullable<int> CoverMin
		{
			get
			{
				return this._CoverMin;
			}
			set
			{
				if ((this._CoverMin != value))
				{
					this._CoverMin = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CoverMax", DbType="Int")]
		public System.Nullable<int> CoverMax
		{
			get
			{
				return this._CoverMax;
			}
			set
			{
				if ((this._CoverMax != value))
				{
					this._CoverMax = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMotorSearch")]
	public partial class tblMotorSearch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CarModelCode;
		
		private string _CarBrandCode;
		
		private string _CarYear;
		
		private string _CarSubModelCode;
		
		private string _CarSubModelName;
		
		private string _CarCCCode;
		
		private string _CarCCName;
		
		private string _txtPolType;
		
		private string _txtInsurer;
		
		private string _txtPremium;
		
		private string _txtLogo;
		
		private string _txtCarType;
		
		private string _txtGarageType;
		
		private string _txtSuminsured;
		
		private string _txtDeduct;
		
		private string _txtGarageCount;
		
		private string _txtCover1;
		
		private string _txtCoverFlood;
		
		private string _txtCarCheck;
		
		private string _txtSubmitID;
		
		private string _txtSubmitStatus;
		
		private string _txtDataC;
		
		private string _txtDataP;
		
		private string _txtDataPV;
		
		private string _txtDataVAT;
		
		private string _txtDataTax;
		
		private string _txtDataAge;
		
		private string _txtComment;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCarModelCodeChanging(string value);
    partial void OnCarModelCodeChanged();
    partial void OnCarBrandCodeChanging(string value);
    partial void OnCarBrandCodeChanged();
    partial void OnCarYearChanging(string value);
    partial void OnCarYearChanged();
    partial void OnCarSubModelCodeChanging(string value);
    partial void OnCarSubModelCodeChanged();
    partial void OnCarSubModelNameChanging(string value);
    partial void OnCarSubModelNameChanged();
    partial void OnCarCCCodeChanging(string value);
    partial void OnCarCCCodeChanged();
    partial void OnCarCCNameChanging(string value);
    partial void OnCarCCNameChanged();
    partial void OntxtPolTypeChanging(string value);
    partial void OntxtPolTypeChanged();
    partial void OntxtInsurerChanging(string value);
    partial void OntxtInsurerChanged();
    partial void OntxtPremiumChanging(string value);
    partial void OntxtPremiumChanged();
    partial void OntxtLogoChanging(string value);
    partial void OntxtLogoChanged();
    partial void OntxtCarTypeChanging(string value);
    partial void OntxtCarTypeChanged();
    partial void OntxtGarageTypeChanging(string value);
    partial void OntxtGarageTypeChanged();
    partial void OntxtSuminsuredChanging(string value);
    partial void OntxtSuminsuredChanged();
    partial void OntxtDeductChanging(string value);
    partial void OntxtDeductChanged();
    partial void OntxtGarageCountChanging(string value);
    partial void OntxtGarageCountChanged();
    partial void OntxtCover1Changing(string value);
    partial void OntxtCover1Changed();
    partial void OntxtCoverFloodChanging(string value);
    partial void OntxtCoverFloodChanged();
    partial void OntxtCarCheckChanging(string value);
    partial void OntxtCarCheckChanged();
    partial void OntxtSubmitIDChanging(string value);
    partial void OntxtSubmitIDChanged();
    partial void OntxtSubmitStatusChanging(string value);
    partial void OntxtSubmitStatusChanged();
    partial void OntxtDataCChanging(string value);
    partial void OntxtDataCChanged();
    partial void OntxtDataPChanging(string value);
    partial void OntxtDataPChanged();
    partial void OntxtDataPVChanging(string value);
    partial void OntxtDataPVChanged();
    partial void OntxtDataVATChanging(string value);
    partial void OntxtDataVATChanged();
    partial void OntxtDataTaxChanging(string value);
    partial void OntxtDataTaxChanged();
    partial void OntxtDataAgeChanging(string value);
    partial void OntxtDataAgeChanged();
    partial void OntxtCommentChanging(string value);
    partial void OntxtCommentChanged();
    #endregion
		
		public tblMotorSearch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarModelCode", DbType="VarChar(50)")]
		public string CarModelCode
		{
			get
			{
				return this._CarModelCode;
			}
			set
			{
				if ((this._CarModelCode != value))
				{
					this.OnCarModelCodeChanging(value);
					this.SendPropertyChanging();
					this._CarModelCode = value;
					this.SendPropertyChanged("CarModelCode");
					this.OnCarModelCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarBrandCode", DbType="VarChar(4)")]
		public string CarBrandCode
		{
			get
			{
				return this._CarBrandCode;
			}
			set
			{
				if ((this._CarBrandCode != value))
				{
					this.OnCarBrandCodeChanging(value);
					this.SendPropertyChanging();
					this._CarBrandCode = value;
					this.SendPropertyChanged("CarBrandCode");
					this.OnCarBrandCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarYear", DbType="VarChar(10)")]
		public string CarYear
		{
			get
			{
				return this._CarYear;
			}
			set
			{
				if ((this._CarYear != value))
				{
					this.OnCarYearChanging(value);
					this.SendPropertyChanging();
					this._CarYear = value;
					this.SendPropertyChanged("CarYear");
					this.OnCarYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarSubModelCode", DbType="VarChar(50)")]
		public string CarSubModelCode
		{
			get
			{
				return this._CarSubModelCode;
			}
			set
			{
				if ((this._CarSubModelCode != value))
				{
					this.OnCarSubModelCodeChanging(value);
					this.SendPropertyChanging();
					this._CarSubModelCode = value;
					this.SendPropertyChanged("CarSubModelCode");
					this.OnCarSubModelCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarSubModelName", DbType="VarChar(255)")]
		public string CarSubModelName
		{
			get
			{
				return this._CarSubModelName;
			}
			set
			{
				if ((this._CarSubModelName != value))
				{
					this.OnCarSubModelNameChanging(value);
					this.SendPropertyChanging();
					this._CarSubModelName = value;
					this.SendPropertyChanged("CarSubModelName");
					this.OnCarSubModelNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarCCCode", DbType="VarChar(50)")]
		public string CarCCCode
		{
			get
			{
				return this._CarCCCode;
			}
			set
			{
				if ((this._CarCCCode != value))
				{
					this.OnCarCCCodeChanging(value);
					this.SendPropertyChanging();
					this._CarCCCode = value;
					this.SendPropertyChanged("CarCCCode");
					this.OnCarCCCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarCCName", DbType="VarChar(50)")]
		public string CarCCName
		{
			get
			{
				return this._CarCCName;
			}
			set
			{
				if ((this._CarCCName != value))
				{
					this.OnCarCCNameChanging(value);
					this.SendPropertyChanging();
					this._CarCCName = value;
					this.SendPropertyChanged("CarCCName");
					this.OnCarCCNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtPolType", DbType="VarChar(255)")]
		public string txtPolType
		{
			get
			{
				return this._txtPolType;
			}
			set
			{
				if ((this._txtPolType != value))
				{
					this.OntxtPolTypeChanging(value);
					this.SendPropertyChanging();
					this._txtPolType = value;
					this.SendPropertyChanged("txtPolType");
					this.OntxtPolTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtInsurer", DbType="VarChar(255)")]
		public string txtInsurer
		{
			get
			{
				return this._txtInsurer;
			}
			set
			{
				if ((this._txtInsurer != value))
				{
					this.OntxtInsurerChanging(value);
					this.SendPropertyChanging();
					this._txtInsurer = value;
					this.SendPropertyChanged("txtInsurer");
					this.OntxtInsurerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtPremium", DbType="VarChar(255)")]
		public string txtPremium
		{
			get
			{
				return this._txtPremium;
			}
			set
			{
				if ((this._txtPremium != value))
				{
					this.OntxtPremiumChanging(value);
					this.SendPropertyChanging();
					this._txtPremium = value;
					this.SendPropertyChanged("txtPremium");
					this.OntxtPremiumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtLogo", DbType="VarChar(255)")]
		public string txtLogo
		{
			get
			{
				return this._txtLogo;
			}
			set
			{
				if ((this._txtLogo != value))
				{
					this.OntxtLogoChanging(value);
					this.SendPropertyChanging();
					this._txtLogo = value;
					this.SendPropertyChanged("txtLogo");
					this.OntxtLogoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtCarType", DbType="VarChar(255)")]
		public string txtCarType
		{
			get
			{
				return this._txtCarType;
			}
			set
			{
				if ((this._txtCarType != value))
				{
					this.OntxtCarTypeChanging(value);
					this.SendPropertyChanging();
					this._txtCarType = value;
					this.SendPropertyChanged("txtCarType");
					this.OntxtCarTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtGarageType", DbType="VarChar(255)")]
		public string txtGarageType
		{
			get
			{
				return this._txtGarageType;
			}
			set
			{
				if ((this._txtGarageType != value))
				{
					this.OntxtGarageTypeChanging(value);
					this.SendPropertyChanging();
					this._txtGarageType = value;
					this.SendPropertyChanged("txtGarageType");
					this.OntxtGarageTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtSuminsured", DbType="VarChar(255)")]
		public string txtSuminsured
		{
			get
			{
				return this._txtSuminsured;
			}
			set
			{
				if ((this._txtSuminsured != value))
				{
					this.OntxtSuminsuredChanging(value);
					this.SendPropertyChanging();
					this._txtSuminsured = value;
					this.SendPropertyChanged("txtSuminsured");
					this.OntxtSuminsuredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtDeduct", DbType="VarChar(255)")]
		public string txtDeduct
		{
			get
			{
				return this._txtDeduct;
			}
			set
			{
				if ((this._txtDeduct != value))
				{
					this.OntxtDeductChanging(value);
					this.SendPropertyChanging();
					this._txtDeduct = value;
					this.SendPropertyChanged("txtDeduct");
					this.OntxtDeductChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtGarageCount", DbType="VarChar(255)")]
		public string txtGarageCount
		{
			get
			{
				return this._txtGarageCount;
			}
			set
			{
				if ((this._txtGarageCount != value))
				{
					this.OntxtGarageCountChanging(value);
					this.SendPropertyChanging();
					this._txtGarageCount = value;
					this.SendPropertyChanged("txtGarageCount");
					this.OntxtGarageCountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtCover1", DbType="VarChar(255)")]
		public string txtCover1
		{
			get
			{
				return this._txtCover1;
			}
			set
			{
				if ((this._txtCover1 != value))
				{
					this.OntxtCover1Changing(value);
					this.SendPropertyChanging();
					this._txtCover1 = value;
					this.SendPropertyChanged("txtCover1");
					this.OntxtCover1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtCoverFlood", DbType="VarChar(255)")]
		public string txtCoverFlood
		{
			get
			{
				return this._txtCoverFlood;
			}
			set
			{
				if ((this._txtCoverFlood != value))
				{
					this.OntxtCoverFloodChanging(value);
					this.SendPropertyChanging();
					this._txtCoverFlood = value;
					this.SendPropertyChanged("txtCoverFlood");
					this.OntxtCoverFloodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtCarCheck", DbType="VarChar(255)")]
		public string txtCarCheck
		{
			get
			{
				return this._txtCarCheck;
			}
			set
			{
				if ((this._txtCarCheck != value))
				{
					this.OntxtCarCheckChanging(value);
					this.SendPropertyChanging();
					this._txtCarCheck = value;
					this.SendPropertyChanged("txtCarCheck");
					this.OntxtCarCheckChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtSubmitID", DbType="VarChar(255)")]
		public string txtSubmitID
		{
			get
			{
				return this._txtSubmitID;
			}
			set
			{
				if ((this._txtSubmitID != value))
				{
					this.OntxtSubmitIDChanging(value);
					this.SendPropertyChanging();
					this._txtSubmitID = value;
					this.SendPropertyChanged("txtSubmitID");
					this.OntxtSubmitIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtSubmitStatus", DbType="VarChar(255)")]
		public string txtSubmitStatus
		{
			get
			{
				return this._txtSubmitStatus;
			}
			set
			{
				if ((this._txtSubmitStatus != value))
				{
					this.OntxtSubmitStatusChanging(value);
					this.SendPropertyChanging();
					this._txtSubmitStatus = value;
					this.SendPropertyChanged("txtSubmitStatus");
					this.OntxtSubmitStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtDataC", DbType="VarChar(255)")]
		public string txtDataC
		{
			get
			{
				return this._txtDataC;
			}
			set
			{
				if ((this._txtDataC != value))
				{
					this.OntxtDataCChanging(value);
					this.SendPropertyChanging();
					this._txtDataC = value;
					this.SendPropertyChanged("txtDataC");
					this.OntxtDataCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtDataP", DbType="VarChar(255)")]
		public string txtDataP
		{
			get
			{
				return this._txtDataP;
			}
			set
			{
				if ((this._txtDataP != value))
				{
					this.OntxtDataPChanging(value);
					this.SendPropertyChanging();
					this._txtDataP = value;
					this.SendPropertyChanged("txtDataP");
					this.OntxtDataPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtDataPV", DbType="VarChar(255)")]
		public string txtDataPV
		{
			get
			{
				return this._txtDataPV;
			}
			set
			{
				if ((this._txtDataPV != value))
				{
					this.OntxtDataPVChanging(value);
					this.SendPropertyChanging();
					this._txtDataPV = value;
					this.SendPropertyChanged("txtDataPV");
					this.OntxtDataPVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtDataVAT", DbType="VarChar(255)")]
		public string txtDataVAT
		{
			get
			{
				return this._txtDataVAT;
			}
			set
			{
				if ((this._txtDataVAT != value))
				{
					this.OntxtDataVATChanging(value);
					this.SendPropertyChanging();
					this._txtDataVAT = value;
					this.SendPropertyChanged("txtDataVAT");
					this.OntxtDataVATChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtDataTax", DbType="VarChar(255)")]
		public string txtDataTax
		{
			get
			{
				return this._txtDataTax;
			}
			set
			{
				if ((this._txtDataTax != value))
				{
					this.OntxtDataTaxChanging(value);
					this.SendPropertyChanging();
					this._txtDataTax = value;
					this.SendPropertyChanged("txtDataTax");
					this.OntxtDataTaxChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtDataAge", DbType="VarChar(255)")]
		public string txtDataAge
		{
			get
			{
				return this._txtDataAge;
			}
			set
			{
				if ((this._txtDataAge != value))
				{
					this.OntxtDataAgeChanging(value);
					this.SendPropertyChanging();
					this._txtDataAge = value;
					this.SendPropertyChanged("txtDataAge");
					this.OntxtDataAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_txtComment", DbType="VarChar(255)")]
		public string txtComment
		{
			get
			{
				return this._txtComment;
			}
			set
			{
				if ((this._txtComment != value))
				{
					this.OntxtCommentChanging(value);
					this.SendPropertyChanging();
					this._txtComment = value;
					this.SendPropertyChanged("txtComment");
					this.OntxtCommentChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblCarSubModelSumInsured")]
	public partial class tblCarSubModelSumInsured : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _CarModelCode;
		
		private string _CarBrandCode;
		
		private string _CarYear;
		
		private string _CarSubModelCode;
		
		private System.Nullable<int> _CarSuminsured;
		
		private string _CarSuminsuredText;
		
		private System.Nullable<int> _IsPost;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnCarModelCodeChanging(string value);
    partial void OnCarModelCodeChanged();
    partial void OnCarBrandCodeChanging(string value);
    partial void OnCarBrandCodeChanged();
    partial void OnCarYearChanging(string value);
    partial void OnCarYearChanged();
    partial void OnCarSubModelCodeChanging(string value);
    partial void OnCarSubModelCodeChanged();
    partial void OnCarSuminsuredChanging(System.Nullable<int> value);
    partial void OnCarSuminsuredChanged();
    partial void OnCarSuminsuredTextChanging(string value);
    partial void OnCarSuminsuredTextChanged();
    partial void OnIsPostChanging(System.Nullable<int> value);
    partial void OnIsPostChanged();
    #endregion
		
		public tblCarSubModelSumInsured()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarModelCode", DbType="VarChar(50)")]
		public string CarModelCode
		{
			get
			{
				return this._CarModelCode;
			}
			set
			{
				if ((this._CarModelCode != value))
				{
					this.OnCarModelCodeChanging(value);
					this.SendPropertyChanging();
					this._CarModelCode = value;
					this.SendPropertyChanged("CarModelCode");
					this.OnCarModelCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarBrandCode", DbType="VarChar(4)")]
		public string CarBrandCode
		{
			get
			{
				return this._CarBrandCode;
			}
			set
			{
				if ((this._CarBrandCode != value))
				{
					this.OnCarBrandCodeChanging(value);
					this.SendPropertyChanging();
					this._CarBrandCode = value;
					this.SendPropertyChanged("CarBrandCode");
					this.OnCarBrandCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarYear", DbType="VarChar(10)")]
		public string CarYear
		{
			get
			{
				return this._CarYear;
			}
			set
			{
				if ((this._CarYear != value))
				{
					this.OnCarYearChanging(value);
					this.SendPropertyChanging();
					this._CarYear = value;
					this.SendPropertyChanged("CarYear");
					this.OnCarYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarSubModelCode", DbType="VarChar(50)")]
		public string CarSubModelCode
		{
			get
			{
				return this._CarSubModelCode;
			}
			set
			{
				if ((this._CarSubModelCode != value))
				{
					this.OnCarSubModelCodeChanging(value);
					this.SendPropertyChanging();
					this._CarSubModelCode = value;
					this.SendPropertyChanged("CarSubModelCode");
					this.OnCarSubModelCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarSuminsured", DbType="Int")]
		public System.Nullable<int> CarSuminsured
		{
			get
			{
				return this._CarSuminsured;
			}
			set
			{
				if ((this._CarSuminsured != value))
				{
					this.OnCarSuminsuredChanging(value);
					this.SendPropertyChanging();
					this._CarSuminsured = value;
					this.SendPropertyChanged("CarSuminsured");
					this.OnCarSuminsuredChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CarSuminsuredText", DbType="VarChar(50)")]
		public string CarSuminsuredText
		{
			get
			{
				return this._CarSuminsuredText;
			}
			set
			{
				if ((this._CarSuminsuredText != value))
				{
					this.OnCarSuminsuredTextChanging(value);
					this.SendPropertyChanging();
					this._CarSuminsuredText = value;
					this.SendPropertyChanged("CarSuminsuredText");
					this.OnCarSuminsuredTextChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsPost", DbType="Int")]
		public System.Nullable<int> IsPost
		{
			get
			{
				return this._IsPost;
			}
			set
			{
				if ((this._IsPost != value))
				{
					this.OnIsPostChanging(value);
					this.SendPropertyChanging();
					this._IsPost = value;
					this.SendPropertyChanged("IsPost");
					this.OnIsPostChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
